Post http://localhost:3001/api/auth/signUp
Content-Type: application/json

{
     "firstName": "ayoubo",  
    "lastName": "iarkane",
    "email":"ayoub9iarkane@gmail.com",
    "password": "ksdn//[{igbernDDrh458",
    "mobile":"0758225437"
}

